<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_Welcome to the Dashboard page manager2</name>
   <tag></tag>
   <elementGuidId>fa55c251-3b88-4cce-a1f6-eb55199b2ffe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h5.text-center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/preceding::h5[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>b4d690e6-1250-4e77-b95b-5c6b7955155d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-center</value>
      <webElementGuid>c5dd8747-8271-469f-9a06-7c63f5fb9374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Welcome to the Dashboard page! manager2!</value>
      <webElementGuid>d4caa624-f728-47c2-a7e4-a92c1ed99564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/h5[@class=&quot;text-center&quot;]</value>
      <webElementGuid>0f38bf02-f74e-4dc2-bab6-1d5bd0983ef3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/preceding::h5[1]</value>
      <webElementGuid>0364d1a6-2e0b-41cc-b94c-6513386b5a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Welcome to the Dashboard page! manager2!']/parent::*</value>
      <webElementGuid>d5f156b8-b13c-4507-aeae-0cb15587a279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5</value>
      <webElementGuid>f7d6d36a-1a25-484a-8c98-0a2434027aef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'Welcome to the Dashboard page! manager2!' or . = 'Welcome to the Dashboard page! manager2!')]</value>
      <webElementGuid>909cf1d8-43cf-40e6-a249-0115d85f017d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
