<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Stock status_is_stocked</name>
   <tag></tag>
   <elementGuidId>714c6083-b658-4deb-a2c4-0800d7511474</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#is_stocked</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='is_stocked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45c9f946-1ebd-4415-b429-5acbed737140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9eef1dda-3c65-4f7d-a349-ec563e70ee39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>is_stocked</value>
      <webElementGuid>6fb1e820-add4-4f89-825e-f42f59fe9efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>is_stocked</value>
      <webElementGuid>9523b6c7-610f-4bba-ab65-710ac2026a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;is_stocked&quot;)</value>
      <webElementGuid>5356f576-4d9a-4e50-a000-89f19e939f29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='is_stocked']</value>
      <webElementGuid>b1bf416e-1bdd-422c-849e-6554467abefe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[2]</value>
      <webElementGuid>1c611044-e03a-43c2-9a9f-fe121e04992e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'is_stocked' and @id = 'is_stocked']</value>
      <webElementGuid>77c5efaa-68c1-464e-adad-04bee14aac43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
