<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__username</name>
   <tag></tag>
   <elementGuidId>623ccf52-bfd3-4945-803b-58e4d24aa857</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_username</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_username']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e2ec94e9-50b7-454e-a5f1-5b96d748b48e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6a209bce-41f4-45c4-a677-c2d2edc87b9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>b0f7f4d3-3d2f-4684-beb9-65773a245b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>150</value>
      <webElementGuid>2c3d12da-9bf2-4c0b-a913-7e2a1b4505c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textinput textInput</value>
      <webElementGuid>071ea6fc-3e80-4a3d-92bd-1d89dd2de02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_username</value>
      <webElementGuid>33707979-4fad-447e-8ae7-eb3e000ef628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_username&quot;)</value>
      <webElementGuid>dcb8cdce-9b3e-41fd-a199-b2fa9b17a148</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_username']</value>
      <webElementGuid>9da05039-b0be-4a61-bb94-11d9cc040844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_username']/div/input</value>
      <webElementGuid>fd696fe2-ae85-4a36-ac49-02cc8af82cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>1f123ca8-4c68-4ddd-af37-14c6888daea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'username' and @id = 'id_username']</value>
      <webElementGuid>eb585458-b4ed-4cbc-9133-b7fe33ae55c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
