<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__bookID</name>
   <tag></tag>
   <elementGuidId>7ac74252-e2d8-4032-b55f-07f38fca5c98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_bookID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_bookID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>093a0ed9-e5c5-41f2-8983-9b6bd95dc1a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5c9e71b-399a-4799-b5cb-480113790ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>bookID</value>
      <webElementGuid>d2ed2de6-4772-4851-97eb-3133899caebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>5adf38d6-d1b7-46fe-9de7-29a07c72a499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textinput textInput</value>
      <webElementGuid>215bbdb4-48a6-41a8-934e-43f21662c895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_bookID</value>
      <webElementGuid>e8916b85-c350-4fbd-80ff-ce6ed6216c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_bookID&quot;)</value>
      <webElementGuid>17299b19-5a20-401c-b90b-c83e1c1b7950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_bookID']</value>
      <webElementGuid>8a13f288-7d90-4f02-a7c5-7f245f8e7fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_bookID']/div/input</value>
      <webElementGuid>45b57cb1-0ae7-4e17-bc46-b73aedff8d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>acda15c5-b9c2-4bc2-ae77-f9245dbcffa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'bookID' and @id = 'id_bookID']</value>
      <webElementGuid>6e9ee918-cf4c-42be-ac46-7f323c864373</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
