<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__language</name>
   <tag></tag>
   <elementGuidId>1aff938f-d6a6-495d-933f-c90a3c55f098</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#id_language</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_language']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5b54a673-7278-46fe-88d2-7763fe91abb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2deada9f-edc2-402d-b298-3a1dd2cf6c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>language</value>
      <webElementGuid>7944f22f-9be7-4ff0-96bc-14a404e359e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f7c8d21d-e022-4dc1-90ec-e528a41393be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textinput textInput</value>
      <webElementGuid>e2154b7b-73d2-4e1c-8367-a252f89f1ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_language</value>
      <webElementGuid>b1f36aa9-e711-4a97-a3b6-c67e50d32e97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_language&quot;)</value>
      <webElementGuid>f588714f-7a9e-4e54-8d23-1aba478a5c2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_language']</value>
      <webElementGuid>6d9c9d5f-1efc-406b-83fe-2ffed4f3e619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_id_language']/div/input</value>
      <webElementGuid>c8bfc1c0-ada2-44c6-8bbc-9d7117d5b44b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>31e87342-2ea6-4f62-b5b2-6ea855211476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'language' and @id = 'id_language']</value>
      <webElementGuid>f87dc4c0-86c1-483d-9fb8-1e0ee7db60ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
